MOV SCON,#50H
MOV TMOD ,#20H
MOV TH1,#0FAH
SETB TR1
START:MOV A,#'M'
      ACALL AGAIN
	  MOV A,#'E'
	  ACALL AGAIN
	  MOV A,#'S'
	  ACALL AGAIN
	  MOV A,#'S'
	  ACALL AGAIN
	  MOV A,#'A'
	  ACALL AGAIN
	  MOV A,#'G'
	  ACALL AGAIN
	  MOV A,#'E'
	  ACALL AGAIN
      SJMP START
AGAIN:MOV SBUF,A
LOOP:JNB TI,LOOP
CLR TI
RET